Broadcasting of Arrays

Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

Rule 1
If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Rule 2
If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

Rule 3
If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [180]:
import numpy as np

In [181]:
# Example 1
M = np.ones((2, 3))
print(M.shape)
print(M)

(2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]


In [182]:
a = np.arange(3)
print(a.shape)
print(a)

(3,)
[0 1 2]


Let’s consider an operation on these two arrays, which have the following shapes:

M.shape is (2, 3)

a.shape is (3,)

We see by rule 1 that the array a has fewer dimensions, so we pad it on the left with ones:

M.shape remains (2, 3)

a.shape becomes (1, 3)

By rule 2, we now see that the first dimension disagrees, so we stretch this dimension to match:

M.shape remains (2, 3)

a.shape becomes (2, 3)

The shapes now match, and we see that the final shape will be (2, 3):

In [184]:
print(M+a)

[[1. 2. 3.]
 [1. 2. 3.]]


In [185]:
# Example 2
a = np.arange(3).reshape((3, 1))
print(a.shape)
print(a)

(3, 1)
[[0]
 [1]
 [2]]


In [186]:
b = np.arange(3)
print(b.shape)
print(b)

(3,)
[0 1 2]


Again, we’ll start by determining the shapes of the arrays:

a.shape is (3, 1)

b.shape is (3,)

Rule 1 says we must pad the shape of b with ones:

a.shape remains (3, 1)

b.shape becomes (1, 3)

And rule 2 tells us that we must upgrade each of these 1s to match the corresponding size of the other array:

a.shape becomes (3, 3)

b.shape becomes (3, 3)

Because the results match, these shapes are compatible. We can see this here:

In [188]:
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [189]:
# Example 3
M = np.ones((3,2))
print(M.shape)
print(M)

(3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [190]:
a = np.arange(3)
print(a.shape)
print(a)

(3,)
[0 1 2]


This is just a slightly different situation than in the first example: the matrix M is transposed. How does this affect the calculation? The shapes of the arrays are as follows:

M.shape is (3, 2)

a.shape is (3,)

Again, rule 1 tells us that we must pad the shape of a with ones:

M.shape remains (3, 2)

a.shape becomes (1, 3)

By rule 2, the first dimension of a is then stretched to match that of M:

M.shape remains (3, 2)

a.shape becomes (3, 3)

Now we hit rule 3—the final shapes do not match, so these two arrays are incompatible, as we can observe by attempting this operation:

In [192]:
# print(M+a)

In [193]:
rng = np.random.default_rng(1701)
X = rng.random((10, 3))
print(X.shape)
print(X)

(10, 3)
[[0.4020733  0.30563311 0.67668051]
 [0.15821208 0.79247763 0.09419469]
 [0.36753944 0.06388928 0.96431608]
 [0.35200998 0.54550343 0.88597945]
 [0.57016965 0.26614394 0.8170382 ]
 [0.55906652 0.06387035 0.84877751]
 [0.89414484 0.18920785 0.23660015]
 [0.16502896 0.56583856 0.29513111]
 [0.29078012 0.90079544 0.59992434]
 [0.09133896 0.00578466 0.97096222]]


In [194]:
Xmean = X.mean(axis=0)
print(Xmean.shape)
print(Xmean)

(3,)
[0.38503638 0.36991443 0.63896043]


In [195]:
Xcentered = X-Xmean
print(Xcentered.shape)
print(Xcentered)

(10, 3)
[[ 0.01703691 -0.06428131  0.03772009]
 [-0.2268243   0.4225632  -0.54476574]
 [-0.01749695 -0.30602514  0.32535566]
 [-0.0330264   0.175589    0.24701902]
 [ 0.18513326 -0.10377048  0.17807777]
 [ 0.17403013 -0.30604408  0.20981709]
 [ 0.50910846 -0.18070657 -0.40236028]
 [-0.22000743  0.19592414 -0.34382932]
 [-0.09425626  0.53088102 -0.03903608]
 [-0.29369742 -0.36412976  0.33200179]]


In [196]:
print(Xcentered.mean(axis=0))

[ 4.99600361e-17 -4.44089210e-17  0.00000000e+00]


Comparison Operators As UFuncs

In [198]:
x = np.array([1, 2, 3, 4, 5])

In [199]:
x < 3

array([ True,  True, False, False, False])

In [200]:
x > 3

array([False, False, False,  True,  True])

In [201]:
x == 3

array([False, False,  True, False, False])

In [202]:
x != 3

array([ True,  True, False,  True,  True])

In [203]:
x <= 3

array([ True,  True,  True, False, False])

In [204]:
x >= 3

array([False, False,  True,  True,  True])

In [205]:
rng = np.random.default_rng(seed=1701)
x = rng.integers(10, size=(3,4))
x

array([[9, 4, 0, 3],
       [8, 6, 3, 1],
       [3, 7, 4, 0]])

In [206]:
x < 6

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

Counting entries

In [230]:
np.count_nonzero(x < 6)

8

Summing entries

In [232]:
np.sum(x < 6)

8

Summing along an axis

In [234]:
# Column-wise sums
np.sum(x < 6, axis=0)

array([1, 1, 3, 3])

In [236]:
# Row-wise sums
np.sum(x < 6, axis=1)

array([3, 2, 3])

Any and All

In [238]:
np.any(x > 8)

True

In [242]:
np.all(x < 8)

False

Any and All have flavors that check along a particular axis

Bitwise Logical Operators

In [244]:
(x < 8) & (x > 3)

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True, False]])

In [246]:
(x < 6) | (x > 2)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

So, remember this: and and or perform a single Boolean evaluation on an entire object, while & and | perform multiple Boolean evaluations on the content (the individual bits or bytes) of an object. For Boolean NumPy arrays, the latter is nearly always the desired operation.