In [1]:
import numpy as np

Print NumPy version

In [2]:
print(np.__version__)

1.26.3


Creating arrays from scratch

In [3]:
# Create a length 10 array filled with 0s
x10 = np.zeros(10, dtype=int)
print(x10)

[0 0 0 0 0 0 0 0 0 0]


In [4]:
# Create a 3x5 floating point array filled with 1s
x35 = np.ones((3, 5), dtype=float)
print(x35)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# Create a 3x5 array filled with Pi
xpi = np.full((3, 5), 3.14)
print(xpi)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [6]:
# Create an array filled with a sequence starting at 0, ending at 20 and steps of 2
xseq = np.arange(0, 20, 2)
print(xseq)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# Create an array of 5 values evenly spaced between 0 and 1
xdist = np.linspace(0, 1, 5)
print(xdist)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
# Create a 3x3 array of uniformly distributed pseudorandom values between 0 and 1
xrand = np.random.random((3, 3))
print(xrand)

[[0.09143472 0.64262891 0.21467455]
 [0.39488652 0.73727345 0.40073537]
 [0.17434765 0.10603119 0.49409877]]


In [9]:
# Create a 3x3 array of normally distributed pseudorandom values with a mean of 0 and standard deviation of 1
xstd = np.random.normal(0, 1, (3, 3))
print(xstd)

[[-0.3829022  -1.30203366 -0.81128457]
 [-0.40736211  0.14771836  0.50679458]
 [-0.68348789  2.28618488  0.62551421]]


In [10]:
# Create a 3x3 matrix of pseudorandom values between 0 and 10
xprand = np.random.randint(0, 10, (3, 3))
print(xprand)

[[8 3 2]
 [9 2 4]
 [7 4 8]]


In [11]:
# Create an identity matrix
xiden = np.eye(3)
print(xiden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a random number generator and seed it

In [12]:
rng = np.random.default_rng(seed=170)

Create 1d, 2d and 3d array

In [13]:
x1 = rng.integers(10, size=6) #1d array
x2 = rng.integers(10, size=(3, 4)) #2d array
x3 = rng.integers(10, size=(3, 4, 5)) #3d array

ndim - number of dimensions, shape - the size of each dimension, size - the total size of the array and dtype - the type of each element

In [14]:
print(f'x3 dim: {x3.ndim}')
print(f'x3 shape: {x3.shape}')
print(f'x3 size: {x3.size}')
print(f'x3 dtype: {x3.dtype}')

x3 dim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int64


Array Indexing

In [15]:
print(f'x1: {x1}')
print(f'{x1[3]}')
print(f'{x1[-1]}')

x1: [7 7 6 9 3 8]
9
8


In [16]:
print(f'x2: {x2}')
print(f'{x2[2, 3]}')
print(f'{x2[0, -1]}')

x2: [[3 9 3 1]
 [7 9 6 0]
 [0 0 2 6]]
6
1


Array Slicing

In [17]:
print(f'x1: {x1}')
print(f'First 3 elements of x1: {x1[:3]}')
print(f'Alternate elements starting with the second element of x1: {x1[1::2]}')
print(f'Alternate elements of x1 starting from the last element: {x1[-1::2]}')

x1: [7 7 6 9 3 8]
First 3 elements of x1: [7 7 6]
Alternate elements starting with the second element of x1: [7 9 8]
Alternate elements of x1 starting from the last element: [8]


Multi-dimensional sub-arrays

In [18]:
print(f'x2: {x2}')
print(f'First 2 rows and 3 columns of x2: {x2[:2, :3]}')
print(f'Every second column of all 3 rows of x2:{x2[:3, ::2]}')
print(f'All rows and columns reversed for x2:{x2[::-1,::-1]}')

x2: [[3 9 3 1]
 [7 9 6 0]
 [0 0 2 6]]
First 2 rows and 3 columns of x2: [[3 9 3]
 [7 9 6]]
Every second column of all 3 rows of x2:[[3 3]
 [7 6]
 [0 2]]
All rows and columns reversed for x2:[[6 2 0 0]
 [0 6 9 7]
 [1 3 9 3]]


Selectively extracting rows and columns

In [19]:
print(f'Last column of x2: {x2[:, -1]}')
print(f'First row of x2: {x2[0, :]}')

Last column of x2: [1 0 6]
First row of x2: [3 9 3 1]


Sub-arrays as No-copy Views

In [20]:
print(f'A 2x2 sub-array extracted from x2 by selecting first two columns of first two rows: {x2[:2, :2]}')
print('Any modifications to elements of the above array will modify the original array (x2) as well.')


A 2x2 sub-array extracted from x2 by selecting first two columns of first two rows: [[3 9]
 [7 9]]
Any modifications to elements of the above array will modify the original array (x2) as well.


Creating copies of Arrays

In [21]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[3 9]
 [7 9]]


Reshaping of Arrays - the size of the initial array must be equal to the size of the re-shaped array.

In [22]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
grid = np.array([x for x in range(1, 10)])
# Reshaping grid to a row vector
print(grid.reshape(1,9))

[[1 2 3 4 5 6 7 8 9]]


In [24]:
# Reshaping row vector to column vector
print(grid.reshape(9, 1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [25]:
print(grid[np.newaxis, :])

[[1 2 3 4 5 6 7 8 9]]


In [26]:
print(grid[:, np.newaxis])

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Concatenation and splitting of Arrays

In [27]:
x1 = np.array([x for x in range(1, 6)])
x2 = np.array([x for x in range(6, 11)])
x_con = np.concatenate([x1, x2])
print(x_con)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
x_grid = np.array([[1, 2, 3],
                   [4, 5, 6]])
x_grid_con = np.concatenate([x_grid, x_grid])
print(x_grid_con)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [29]:
x_grid_con = np.concatenate([x_grid, x_grid], axis=1)
print(x_grid_con)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [30]:
x_vstack = np.vstack([x1, x2])
print(x_vstack)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
x_hstack = np.hstack([x1, x2])
print(x_hstack)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
x1, x2, x3 = np.split(x_hstack, [3, 6])
print(x1, x2, x3)

[1 2 3] [4 5 6] [ 7  8  9 10]


In [33]:
grid = np.arange(16).reshape(4, 4)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [34]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
